import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/sections/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          md: "2rem",
          lg: "4rem",
        },
      },
      fontFamily: {
        sans: ["var(--font-poppins)", "sans-serif"],
      },
      screens: {
        sm: "375px",
        md: "768px",
        lg: "1200px",
      },
      colors: {
        text: {
          DEFAULT: "#000000",
          blackPrimary: "#222222",
          blackSecondary: "#464646",
          blackTertiary: "#AFAFAF",
          whitePrimary: "#F9F9F9",
          whiteSecondary: "##E5E5E5",
          purple1: "#7347FF",
          purple2: "#5D39D2",
        },
        background: {
          DEFAULT: "#F9FAFB",
          white: "#F9F4F4",
          gradientPrimary: "linear-gradient(to right, #E8E1FF, #FFEADB)",
          gradientSecondary: "linear-gradient(to right, #CFC1FF, #FFE1CC)",
        },
        primary: {
          DEFAULT: "#2563EB",
          primary50: "#F1EDFF",
          primary100: "#E3DAFF",
          primary200: "#C7B5FF",
          primary300: "#AB91FF",
          primary400: "#8F6CFF",
          primary500: "#7347FF",
          primary600: "#5D39D2",
          primary700: "#482BA5",
          primary800: "#321C78",
          primary900: "#1D0E4B",
        },
        secondary: {
          DEFAULT: "#10B981",
          secondary50: "#FFF7F1",
          secondary100: "#FFEEE3",
          secondary200: "#FFDEC6",
          secondary300: "#FFCDAA",
          secondary400: "#FFBD8D",
          secondary500: "#FFAC71",
          secondary600: "#DA905A",
          secondary700: "#B67344",
          secondary800: "#91572D",
          secondary900: "#6D3A17",
        },
        tertiary: {
          DEFAULT: "#F59E0B",
          tertiary50: "#F5F5F5",
          tertiary100: "#EBEBEB",
          tertiary200: "#D8D8D8",
          tertiary300: "#C4C4C4",
          tertiary400: "#B1B1B1",
          tertiary500: "#9D9D9D",
          tertiary600: "#7F7F7F",
          tertiary700: "#626262",
          tertiary800: "#444444",
          tertiary900: "#272727",
        },
        others: {
          stack: "#909086",
          blueChalk: "#E8E1FF",
          karry: "#FFEADB",
          perfume: "#CFC1FF",
          tuftBush: "#FFE1CC",
          santasGray: "#A09EA8",
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
